add footer
ViktoriiaTsikalo/project-ProDev23 pull request #5
Opened 2024-11-19 01:01 UTC by olga-magnusson

2024-11-19 09:04 UTC, ViktoriiaTsikalo requested changes
Треба доопрацювати

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/partials/footer.html
> +      <address class="tel">
Телефон не має бути курсивом, як у Вас

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/partials/footer.html
> +          <li class="socialmedia-icon">
Іконки у Вас не в центрі боксів і занадто маленькі. Шлях до іконок і зображень потрібно вказувати без крапок, про це розповідали на занятті.

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/partials/footer.html
> +        <p>©2023 The Watch Spot. All rights reserved.</p>
Знак © краще прописати юнікодом

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/partials/footer.html
> +          <a href="">1678 S. Pioneer Road Salt Lake City UT 84104</a>
Тут теж не має бути курсива

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/css/footer.css
> +  border: 1px solid rgba(251, 251, 251, 0.2);
У шаблоні менша прозорізть лінії stroke: rgba(251, 251, 251, 0.1);

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/css/footer.css
> +.footer {
При мобільній і планшетній верхіях занадто велика відстань всередині. Там треба налаштувати фіксовані марджини. При розтягуванні і стягуванні все кудись розпливається.

2024-11-19 09:04 UTC, ViktoriiaTsikalo commented on src/partials/footer.html
> +  <div class="footer" id="footer">
Після класу footer  треба додати клас container, властивості якого я вже налаштувала. Це не дозволятиме елементам розпливатись.

2024-11-19 21:09 UTC, olga-magnusson commented on src/partials/footer.html
> +      <address class="tel">
Виправлено

2024-11-19 21:10 UTC, olga-magnusson commented on src/partials/footer.html
> +          <li class="socialmedia-icon">
Виправлено

2024-11-19 21:10 UTC, olga-magnusson commented on src/css/footer.css
> +.footer {
Виправлено, але зверніть увагу при перевірці, я не впевнена що працює правильно. Дякую.

2024-11-19 21:10 UTC, olga-magnusson commented on src/partials/footer.html
> +        <p>©2023 The Watch Spot. All rights reserved.</p>
Виправлено

2024-11-19 21:10 UTC, olga-magnusson commented on src/partials/footer.html
> +          <a href="">1678 S. Pioneer Road Salt Lake City UT 84104</a>
Виправлено

2024-11-19 21:10 UTC, olga-magnusson commented on src/css/footer.css
> +  border: 1px solid rgba(251, 251, 251, 0.2);
Виправлено

2024-11-19 21:10 UTC, olga-magnusson commented on src/partials/footer.html
> +  <div class="footer" id="footer">
Виправлено

2024-11-19 21:12 UTC, olga-magnusson commented
допрацювала і виправила помилки, 

"При мобільній і планшетній верхіях занадто велика відстань всередині. Там треба налаштувати фіксовані марджини. При розтягуванні і стягуванні все кудись розпливається."

зверніть увагу при перевірці, я не впевнена що працює правильно. 

Дякую.

2024-11-20 13:23 UTC, ViktoriiaTsikalo approved these changes
Добре

2024-11-20 13:23 UTC, merged